
export const REQUEST_PROFILE = 'REQUEST_PROFILE'
export const RECEIVE_PROFILE = 'RECEIVE_PROFILE'
export const FETCH_POSTS_FAILURE ='FETCH_POSTS_FAILURE'
export const FETCH_SINGLE_PROFILE ='FETCH_SINGLE_PROFILE'