
export const REQUEST_PROFILE = 'REQUEST_PROFILE'
export const RECEIVE_PROFILE = 'RECEIVE_PROFILE'
export const FETCH_SINGLE_PROFILE ='FETCH_SINGLE_PROFILE'
export const CREATE_NEW_CANDIDATE = 'CREATE_NEW_CANDIDATE'
export const UPDATE_CANDIDATE = 'UPDATE_CANDIDATE'
export const DELETE_CANDIDATE = 'DELETE_CONTACT'